services:
  api:
    build:
      context: .
      dockerfile: docker/go/Dockerfile.dev
    container_name: go_api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
