services:
  api:
    build:
      context: .
      dockerfile: docker/go/Dockerfile.dev
    container_name: go_api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=book_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
